import {
  Agent,
  Customer,
  Lead,
  RecoveryCase,
  Task,
  Call,
  Payment,
  CrmDocument,
  CrmNotification,
  ActivityEvent,
  Communication
} from '../models';

export const MOCK_AGENTS: Agent[] = [
  {
    id: 'agent-1',
    employeeId: 'TFR-AGT-001',
    firstName: 'Marcus',
    lastName: 'Vance',
    email: 'marcus.vance@trustfundsrecovery.com',
    phone: '+1 (555) 234-8901',
    role: 'Senior Recovery Specialist',
    department: 'Tax Foreclosure Recovery',
    status: 'active',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    dateJoined: '2023-03-15',
    lastActive: '2026-09-18T09:42:00Z',
    assignedCustomers: 18,
    activeCases: 12,
    completedCases: 34,
    pendingTasks: 7,
    completedTasks: 89,
    callsMade: 342,
    callsConnected: 215,
    callsMissed: 127
  },
  {
    id: 'agent-2',
    employeeId: 'TFR-AGT-002',
    firstName: 'Elena',
    lastName: 'Rostova',
    email: 'elena.rostova@trustfundsrecovery.com',
    phone: '+1 (555) 345-6712',
    role: 'Lead Case Manager',
    department: 'Mortgage Surplus Division',
    status: 'active',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    dateJoined: '2023-06-01',
    lastActive: '2026-09-18T10:15:00Z',
    assignedCustomers: 22,
    activeCases: 15,
    completedCases: 48,
    pendingTasks: 4,
    completedTasks: 112,
    callsMade: 480,
    callsConnected: 310,
    callsMissed: 170
  },
  {
    id: 'agent-3',
    employeeId: 'TFR-AGT-003',
    firstName: 'David',
    lastName: 'Sterling',
    email: 'david.sterling@trustfundsrecovery.com',
    phone: '+1 (555) 456-7823',
    role: 'Recovery Specialist',
    department: 'Unclaimed Property & Escrow',
    status: 'active',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    dateJoined: '2024-01-10',
    lastActive: '2026-09-18T08:50:00Z',
    assignedCustomers: 14,
    activeCases: 9,
    completedCases: 19,
    pendingTasks: 9,
    completedTasks: 62,
    callsMade: 290,
    callsConnected: 180,
    callsMissed: 110
  },
  {
    id: 'agent-4',
    employeeId: 'TFR-AGT-004',
    firstName: 'Sarah',
    lastName: 'Jenkins',
    email: 'sarah.jenkins@trustfundsrecovery.com',
    phone: '+1 (555) 567-8934',
    role: 'Junior Intake Specialist',
    department: 'Client Onboarding',
    status: 'active',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    dateJoined: '2024-07-20',
    lastActive: '2026-09-18T11:05:00Z',
    assignedCustomers: 11,
    activeCases: 6,
    completedCases: 8,
    pendingTasks: 12,
    completedTasks: 41,
    callsMade: 395,
    callsConnected: 230,
    callsMissed: 165
  },
  {
    id: 'agent-5',
    employeeId: 'TFR-AGT-005',
    firstName: 'Robert',
    lastName: 'Chen',
    email: 'robert.chen@trustfundsrecovery.com',
    phone: '+1 (555) 678-9045',
    role: 'Legal Liaison & Recovery Officer',
    department: 'Judicial & Court Filings',
    status: 'active',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    dateJoined: '2023-09-01',
    lastActive: '2026-09-17T16:40:00Z',
    assignedCustomers: 15,
    activeCases: 11,
    completedCases: 29,
    pendingTasks: 5,
    completedTasks: 78,
    callsMade: 195,
    callsConnected: 140,
    callsMissed: 55
  },
  {
    id: 'agent-6',
    employeeId: 'TFR-AGT-006',
    firstName: 'Jessica',
    lastName: 'Taylor',
    email: 'jessica.taylor@trustfundsrecovery.com',
    phone: '+1 (555) 789-0156',
    role: 'Recovery Specialist',
    department: 'Mortgage Surplus Division',
    status: 'on_leave',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    dateJoined: '2023-11-15',
    lastActive: '2026-09-10T12:00:00Z',
    assignedCustomers: 8,
    activeCases: 4,
    completedCases: 15,
    pendingTasks: 2,
    completedTasks: 45,
    callsMade: 180,
    callsConnected: 110,
    callsMissed: 70
  }
];

export const MOCK_CUSTOMERS: Customer[] = [
  {
    id: 'cust-1',
    customerNumber: 'CUST-1001',
    firstName: 'Arthur',
    lastName: 'Pendleton',
    fullName: 'Arthur Pendleton',
    email: 'arthur.p@example.com',
    phone: '+1 (415) 892-3491',
    maskedPhone: '+1 (***) ***-3491',
    address: { street: '742 Evergreen Terrace', city: 'Sacramento', state: 'CA', postalCode: '95814', country: 'USA' },
    status: 'active',
    assignedAgentId: 'agent-1',
    assignedAgentName: 'Marcus Vance',
    totalClaimAmount: 84500,
    totalRecoveredAmount: 84500,
    claimType: 'Tax Deed Surplus',
    dateAdded: '2026-01-12T09:00:00Z',
    lastContactedDate: '2026-09-15T14:20:00Z',
    notes: 'Surplus funds verified with Sacramento County Superior Court. Client signed retainer.',
    activeCasesCount: 1,
    totalCasesCount: 1,
    tags: ['Verified', 'High Value', 'Tax Sale']
  },
  {
    id: 'cust-2',
    customerNumber: 'CUST-1002',
    firstName: 'Beatrice',
    lastName: 'Montgomery',
    fullName: 'Beatrice Montgomery',
    email: 'bmontgomery@example.com',
    phone: '+1 (305) 714-8820',
    maskedPhone: '+1 (***) ***-8820',
    address: { street: '120 Ocean Drive, Apt 4B', city: 'Miami', state: 'FL', postalCode: '33139', country: 'USA' },
    status: 'active',
    assignedAgentId: 'agent-2',
    assignedAgentName: 'Elena Rostova',
    totalClaimAmount: 142000,
    totalRecoveredAmount: 0,
    claimType: 'Mortgage Foreclosure Overage',
    dateAdded: '2026-02-04T11:30:00Z',
    lastContactedDate: '2026-09-17T16:00:00Z',
    notes: 'Foreclosure sale generated significant surplus. Miami-Dade Clerk holding funds.',
    activeCasesCount: 1,
    totalCasesCount: 1,
    tags: ['Foreclosure', 'Escrow Check']
  },
  {
    id: 'cust-3',
    customerNumber: 'CUST-1003',
    firstName: 'Charles',
    lastName: 'Gallagher',
    fullName: 'Charles Gallagher',
    email: 'c.gallagher@example.com',
    phone: '+1 (512) 640-1928',
    maskedPhone: '+1 (***) ***-1928',
    address: { street: '890 Barton Springs Rd', city: 'Austin', state: 'TX', postalCode: '78704', country: 'USA' },
    status: 'active',
    assignedAgentId: 'agent-3',
    assignedAgentName: 'David Sterling',
    totalClaimAmount: 56300,
    totalRecoveredAmount: 56300,
    claimType: 'Tax Sale Surplus',
    dateAdded: '2026-03-10T14:15:00Z',
    lastContactedDate: '2026-09-12T10:45:00Z',
    notes: 'Travis County registry disbars surplus check. Disbursed successfully to client.',
    activeCasesCount: 0,
    totalCasesCount: 1,
    tags: ['Completed', 'Satisfied']
  },
  {
    id: 'cust-4',
    customerNumber: 'CUST-1004',
    firstName: 'Diana',
    lastName: 'Kaufman',
    fullName: 'Diana Kaufman',
    email: 'dkaufman99@example.com',
    phone: '+1 (602) 492-6715',
    maskedPhone: '+1 (***) ***-6715',
    address: { street: '4410 Camelback Mountain Way', city: 'Phoenix', state: 'AZ', postalCode: '85018', country: 'USA' },
    status: 'active',
    assignedAgentId: 'agent-1',
    assignedAgentName: 'Marcus Vance',
    totalClaimAmount: 118400,
    totalRecoveredAmount: 0,
    claimType: 'Unclaimed Property & Escrow',
    dateAdded: '2026-04-18T08:20:00Z',
    lastContactedDate: '2026-09-18T09:10:00Z',
    notes: 'Maricopa County treasurer holding excess proceeds. Motion for release submitted.',
    activeCasesCount: 1,
    totalCasesCount: 1,
    tags: ['Motion Filed', 'Maricopa']
  },
  {
    id: 'cust-5',
    customerNumber: 'CUST-1005',
    firstName: 'Edward',
    lastName: 'Norton-Smith',
    fullName: 'Edward Norton-Smith',
    email: 'ed.nortonsmith@example.com',
    phone: '+1 (702) 381-9940',
    maskedPhone: '+1 (***) ***-9940',
    address: { street: '210 Red Rock Vista', city: 'Las Vegas', state: 'NV', postalCode: '89138', country: 'USA' },
    status: 'pending',
    assignedAgentId: 'agent-4',
    assignedAgentName: 'Sarah Jenkins',
    totalClaimAmount: 43200,
    totalRecoveredAmount: 0,
    claimType: 'Mortgage Foreclosure Overage',
    dateAdded: '2026-05-02T13:00:00Z',
    lastContactedDate: '2026-09-14T11:00:00Z',
    notes: 'Awaiting notarized proof of identity and utility bill from client.',
    activeCasesCount: 1,
    totalCasesCount: 1,
    tags: ['Docs Pending']
  },
  {
    id: 'cust-6',
    customerNumber: 'CUST-1006',
    firstName: 'Fiona',
    lastName: 'O\'Connor',
    fullName: 'Fiona O\'Connor',
    email: 'foconnor@example.com',
    phone: '+1 (206) 881-2291',
    maskedPhone: '+1 (***) ***-2291',
    address: { street: '335 Queen Anne Ave N', city: 'Seattle', state: 'WA', postalCode: '98109', country: 'USA' },
    status: 'active',
    assignedAgentId: 'agent-2',
    assignedAgentName: 'Elena Rostova',
    totalClaimAmount: 95700,
    totalRecoveredAmount: 0,
    claimType: 'Tax Deed Surplus',
    dateAdded: '2026-05-22T10:00:00Z',
    lastContactedDate: '2026-09-16T15:30:00Z',
    notes: 'King County Superior Court case scheduled for auditor review next week.',
    activeCasesCount: 1,
    totalCasesCount: 1,
    tags: ['Hearing Scheduled']
  },
  {
    id: 'cust-7',
    customerNumber: 'CUST-1007',
    firstName: 'George',
    lastName: 'Holloway',
    fullName: 'George Holloway',
    email: 'gholloway@example.com',
    phone: '+1 (404) 923-5501',
    maskedPhone: '+1 (***) ***-5501',
    address: { street: '150 Peachtree St NE', city: 'Atlanta', state: 'GA', postalCode: '30303', country: 'USA' },
    status: 'active',
    assignedAgentId: 'agent-5',
    assignedAgentName: 'Robert Chen',
    totalClaimAmount: 67800,
    totalRecoveredAmount: 67800,
    claimType: 'Tax Sale Surplus',
    dateAdded: '2026-06-11T12:00:00Z',
    lastContactedDate: '2026-09-08T09:20:00Z',
    notes: 'Fulton County sheriff sale overage collected and disbursed.',
    activeCasesCount: 0,
    totalCasesCount: 1,
    tags: ['Completed']
  },
  {
    id: 'cust-8',
    customerNumber: 'CUST-1008',
    firstName: 'Hannah',
    lastName: 'Lindqvist',
    fullName: 'Hannah Lindqvist',
    email: 'hlindqvist@example.com',
    phone: '+1 (312) 554-9012',
    maskedPhone: '+1 (***) ***-9012',
    address: { street: '600 N Michigan Ave', city: 'Chicago', state: 'IL', postalCode: '60611', country: 'USA' },
    status: 'active',
    assignedAgentId: 'agent-2',
    assignedAgentName: 'Elena Rostova',
    totalClaimAmount: 185000,
    totalRecoveredAmount: 0,
    claimType: 'Mortgage Foreclosure Overage',
    dateAdded: '2026-06-30T16:40:00Z',
    lastContactedDate: '2026-09-17T11:15:00Z',
    notes: 'Cook County judicial sale excess proceeds. Largest pending claim this quarter.',
    activeCasesCount: 1,
    totalCasesCount: 1,
    tags: ['High Value', 'Cook County']
  },
  {
    id: 'cust-9',
    customerNumber: 'CUST-1009',
    firstName: 'Ian',
    lastName: 'Thornton',
    fullName: 'Ian Thornton',
    email: 'ithornton@example.com',
    phone: '+1 (303) 441-7603',
    maskedPhone: '+1 (***) ***-7603',
    address: { street: '1700 28th St', city: 'Boulder', state: 'CO', postalCode: '80301', country: 'USA' },
    status: 'pending',
    assignedAgentId: 'agent-3',
    assignedAgentName: 'David Sterling',
    totalClaimAmount: 38900,
    totalRecoveredAmount: 0,
    claimType: 'Unclaimed Property & Escrow',
    dateAdded: '2026-07-14T09:15:00Z',
    lastContactedDate: '2026-09-11T13:45:00Z',
    notes: 'Colorado State Treasury unclaimed funds inquiry filed. Waiting on state review.',
    activeCasesCount: 1,
    totalCasesCount: 1,
    tags: ['State Treasury']
  },
  {
    id: 'cust-10',
    customerNumber: 'CUST-1010',
    firstName: 'Jacqueline',
    lastName: 'Mercer',
    fullName: 'Jacqueline Mercer',
    email: 'j.mercer@example.com',
    phone: '+1 (214) 732-9844',
    maskedPhone: '+1 (***) ***-9844',
    address: { street: '2400 McKinney Ave', city: 'Dallas', state: 'TX', postalCode: '75201', country: 'USA' },
    status: 'active',
    assignedAgentId: 'agent-1',
    assignedAgentName: 'Marcus Vance',
    totalClaimAmount: 72400,
    totalRecoveredAmount: 0,
    claimType: 'Tax Deed Surplus',
    dateAdded: '2026-07-28T14:50:00Z',
    lastContactedDate: '2026-09-18T10:00:00Z',
    notes: 'Dallas County tax collector notified. Claim packet submitted.',
    activeCasesCount: 1,
    totalCasesCount: 1,
    tags: ['Tax Surplus', 'Texas']
  },
  {
    id: 'cust-11',
    customerNumber: 'CUST-1011',
    firstName: 'Kenneth',
    lastName: 'Bauer',
    fullName: 'Kenneth Bauer',
    email: 'kbauer@example.com',
    phone: '+1 (617) 491-3320',
    maskedPhone: '+1 (***) ***-3320',
    address: { street: '85 Commonwealth Ave', city: 'Boston', state: 'MA', postalCode: '02116', country: 'USA' },
    status: 'resolved',
    assignedAgentId: 'agent-5',
    assignedAgentName: 'Robert Chen',
    totalClaimAmount: 112000,
    totalRecoveredAmount: 112000,
    claimType: 'Mortgage Foreclosure Overage',
    dateAdded: '2026-03-01T08:00:00Z',
    lastContactedDate: '2026-08-25T15:00:00Z',
    notes: 'Full surplus recovered from Land Court. Contingency fee collected.',
    activeCasesCount: 0,
    totalCasesCount: 1,
    tags: ['Resolved', 'VIP']
  },
  {
    id: 'cust-12',
    customerNumber: 'CUST-1012',
    firstName: 'Laura',
    lastName: 'Whitaker',
    fullName: 'Laura Whitaker',
    email: 'lwhitaker@example.com',
    phone: '+1 (813) 609-4411',
    maskedPhone: '+1 (***) ***-4411',
    address: { street: '400 Bayshore Blvd', city: 'Tampa', state: 'FL', postalCode: '33606', country: 'USA' },
    status: 'active',
    assignedAgentId: 'agent-4',
    assignedAgentName: 'Sarah Jenkins',
    totalClaimAmount: 49500,
    totalRecoveredAmount: 0,
    claimType: 'Tax Sale Surplus',
    dateAdded: '2026-08-10T11:00:00Z',
    lastContactedDate: '2026-09-16T09:30:00Z',
    notes: 'Hillsborough County tax surplus claim signed and filed.',
    activeCasesCount: 1,
    totalCasesCount: 1,
    tags: ['Florida', 'Tax Sale']
  }
];

export const MOCK_LEADS: Lead[] = [
  {
    id: 'lead-1',
    leadNumber: 'LEAD-2001',
    firstName: 'Victor',
    lastName: 'Delgado',
    fullName: 'Victor Delgado',
    email: 'vdelgado@sample.com',
    phone: '+1 (714) 555-0199',
    maskedPhone: '+1 (***) ***-0199',
    propertyAddress: '1420 Newport Blvd, Costa Mesa, CA',
    state: 'CA',
    county: 'Orange',
    estimatedOverage: 134000,
    surplusType: 'Mortgage Foreclosure',
    stage: 'contract_sent',
    status: 'active',
    score: 92,
    source: 'County Records',
    assignedAgentId: 'agent-1',
    assignedAgentName: 'Marcus Vance',
    dateAdded: '2026-08-01T10:00:00Z',
    lastContactDate: '2026-09-17T14:30:00Z',
    notes: 'High equity overage. Contract delivered via DocuSign; follow up today.'
  },
  {
    id: 'lead-2',
    leadNumber: 'LEAD-2002',
    firstName: 'Samantha',
    lastName: 'Garrison',
    fullName: 'Samantha Garrison',
    email: 'sgarrison@sample.com',
    phone: '+1 (407) 555-0144',
    maskedPhone: '+1 (***) ***-0144',
    propertyAddress: '782 Orange Blossom Trail, Orlando, FL',
    state: 'FL',
    county: 'Orange',
    estimatedOverage: 78500,
    surplusType: 'Tax Deed Surplus',
    stage: 'contacted',
    status: 'active',
    score: 84,
    source: 'Skip Trace',
    assignedAgentId: 'agent-2',
    assignedAgentName: 'Elena Rostova',
    dateAdded: '2026-08-12T11:20:00Z',
    lastContactDate: '2026-09-16T16:00:00Z',
    notes: 'Left voicemail explaining overage entitlement. Call scheduled for tomorrow.'
  },
  {
    id: 'lead-3',
    leadNumber: 'LEAD-2003',
    firstName: 'Franklin',
    lastName: 'Manning',
    fullName: 'Franklin Manning',
    email: 'fmanning@sample.com',
    phone: '+1 (832) 555-0128',
    maskedPhone: '+1 (***) ***-0128',
    propertyAddress: '5501 Memorial Dr, Houston, TX',
    state: 'TX',
    county: 'Harris',
    estimatedOverage: 215000,
    surplusType: 'Mortgage Foreclosure',
    stage: 'interested',
    status: 'active',
    score: 96,
    source: 'County Records',
    assignedAgentId: 'agent-1',
    assignedAgentName: 'Marcus Vance',
    dateAdded: '2026-08-18T09:00:00Z',
    lastContactDate: '2026-09-18T10:30:00Z',
    notes: 'Very receptive on phone. Wants to see contingency agreement before proceeding.'
  },
  {
    id: 'lead-4',
    leadNumber: 'LEAD-2004',
    firstName: 'Miriam',
    lastName: 'Goldstein',
    fullName: 'Miriam Goldstein',
    email: 'mgoldstein@sample.com',
    phone: '+1 (702) 555-0182',
    maskedPhone: '+1 (***) ***-0182',
    propertyAddress: '1100 S Las Vegas Blvd, Las Vegas, NV',
    state: 'NV',
    county: 'Clark',
    estimatedOverage: 62000,
    surplusType: 'Tax Deed Surplus',
    stage: 'new',
    status: 'active',
    score: 75,
    source: 'Public Auction Records',
    assignedAgentId: 'agent-4',
    assignedAgentName: 'Sarah Jenkins',
    dateAdded: '2026-09-02T13:40:00Z',
    lastContactDate: undefined,
    notes: 'Fresh lead from Clark County auction report. Needs first outreach.'
  },
  {
    id: 'lead-5',
    leadNumber: 'LEAD-2005',
    firstName: 'Timothy',
    lastName: 'Whelan',
    fullName: 'Timothy Whelan',
    email: 'twhelan@sample.com',
    phone: '+1 (206) 555-0177',
    maskedPhone: '+1 (***) ***-0177',
    propertyAddress: '904 Rainier Ave S, Seattle, WA',
    state: 'WA',
    county: 'King',
    estimatedOverage: 91000,
    surplusType: 'Tax Deed Surplus',
    stage: 'contract_signed',
    status: 'active',
    score: 98,
    source: 'Website Form',
    assignedAgentId: 'agent-2',
    assignedAgentName: 'Elena Rostova',
    dateAdded: '2026-08-25T08:15:00Z',
    lastContactDate: '2026-09-17T09:00:00Z',
    notes: 'Contract signed! Ready for conversion to active customer and case creation.'
  },
  {
    id: 'lead-6',
    leadNumber: 'LEAD-2006',
    firstName: 'Candace',
    lastName: 'Owensby',
    fullName: 'Candace Owensby',
    email: 'cowensby@sample.com',
    phone: '+1 (480) 555-0163',
    maskedPhone: '+1 (***) ***-0163',
    propertyAddress: '312 N Scottsdale Rd, Scottsdale, AZ',
    state: 'AZ',
    county: 'Maricopa',
    estimatedOverage: 45000,
    surplusType: 'Unclaimed Estate',
    stage: 'contacted',
    status: 'active',
    score: 68,
    source: 'Skip Trace',
    assignedAgentId: 'agent-3',
    assignedAgentName: 'David Sterling',
    dateAdded: '2026-09-05T15:00:00Z',
    lastContactDate: '2026-09-15T11:45:00Z',
    notes: 'Needs family tree verification. Heirs are reviewing documents.'
  },
  {
    id: 'lead-7',
    leadNumber: 'LEAD-2007',
    firstName: 'Gregory',
    lastName: 'Shaw',
    fullName: 'Gregory Shaw',
    email: 'gshaw@sample.com',
    phone: '+1 (916) 555-0119',
    maskedPhone: '+1 (***) ***-0119',
    propertyAddress: '2300 K St, Sacramento, CA',
    state: 'CA',
    county: 'Sacramento',
    estimatedOverage: 110000,
    surplusType: 'Mortgage Foreclosure',
    stage: 'unqualified',
    status: 'bad_lead',
    score: 25,
    source: 'County Records',
    assignedAgentId: 'agent-1',
    assignedAgentName: 'Marcus Vance',
    dateAdded: '2026-07-20T10:00:00Z',
    lastContactDate: '2026-08-05T14:00:00Z',
    notes: 'Junior lienholder exhausted all surplus funds. No remaining recovery available.'
  },
  {
    id: 'lead-8',
    leadNumber: 'LEAD-2008',
    firstName: 'Patricia',
    lastName: 'Monroe',
    fullName: 'Patricia Monroe',
    email: 'pmonroe@sample.com',
    phone: '+1 (678) 555-0131',
    maskedPhone: '+1 (***) ***-0131',
    propertyAddress: '422 Piedmont Ave, Atlanta, GA',
    state: 'GA',
    county: 'Fulton',
    estimatedOverage: 83000,
    surplusType: 'Tax Deed Surplus',
    stage: 'interested',
    status: 'active',
    score: 87,
    source: 'Website Form',
    assignedAgentId: 'agent-4',
    assignedAgentName: 'Sarah Jenkins',
    dateAdded: '2026-09-10T11:15:00Z',
    lastContactDate: '2026-09-17T15:20:00Z',
    notes: 'Submitted inquiry on website. Confirmed identity; preparing agreement.'
  }
];

export const MOCK_CASES: RecoveryCase[] = [
  {
    id: 'case-1',
    caseNumber: 'TRF-5011',
    customerId: 'cust-1',
    customerName: 'Arthur Pendleton',
    title: 'Sacramento County Tax Surplus Recovery',
    claimType: 'Tax Deed Surplus',
    status: 'completed',
    priority: 'high',
    claimAmount: 84500,
    expectedFee: 21125,
    feePercentage: 25,
    recoveredAmount: 84500,
    assignedAgentId: 'agent-1',
    assignedAgentName: 'Marcus Vance',
    filingJurisdiction: 'Sacramento County Superior Court',
    caseRefNumber: '34-2026-003891',
    filingDate: '2026-02-10',
    hearingDate: '2026-04-15',
    dateCreated: '2026-01-15T10:00:00Z',
    lastUpdated: '2026-05-20T14:30:00Z',
    description: 'Surplus recovery following judicial tax deed auction on residential property.',
    notes: 'Funds released by county auditor and disbursed to client.'
  },
  {
    id: 'case-2',
    caseNumber: 'TRF-5012',
    customerId: 'cust-2',
    customerName: 'Beatrice Montgomery',
    title: 'Miami-Dade Foreclosure Excess Funds Recovery',
    claimType: 'Mortgage Foreclosure Overage',
    status: 'recovery_processing',
    priority: 'urgent',
    claimAmount: 142000,
    expectedFee: 35500,
    feePercentage: 25,
    recoveredAmount: 0,
    assignedAgentId: 'agent-2',
    assignedAgentName: 'Elena Rostova',
    filingJurisdiction: '11th Judicial Circuit Court of Florida',
    caseRefNumber: '2026-CA-019482',
    filingDate: '2026-03-01',
    hearingDate: '2026-09-25',
    dateCreated: '2026-02-05T09:30:00Z',
    lastUpdated: '2026-09-17T16:00:00Z',
    description: 'First mortgage lien satisfied; substantial surplus in court registry.',
    notes: 'Hearing set for next week. Certificate of Title and disbursements ordered.'
  },
  {
    id: 'case-3',
    caseNumber: 'TRF-5013',
    customerId: 'cust-4',
    customerName: 'Diana Kaufman',
    title: 'Maricopa County Excess Proceeds Claim',
    claimType: 'Unclaimed Property & Escrow',
    status: 'in_progress',
    priority: 'high',
    claimAmount: 118400,
    expectedFee: 29600,
    feePercentage: 25,
    recoveredAmount: 0,
    assignedAgentId: 'agent-1',
    assignedAgentName: 'Marcus Vance',
    filingJurisdiction: 'Maricopa County Treasurer Department',
    caseRefNumber: 'TX-2025-08129',
    filingDate: '2026-05-10',
    hearingDate: undefined,
    dateCreated: '2026-04-20T11:00:00Z',
    lastUpdated: '2026-09-18T09:10:00Z',
    description: 'Claim filed with treasurer for surplus trustee sale proceeds.',
    notes: 'County treasurer requested certified deed copy; submitted on Sept 12.'
  },
  {
    id: 'case-4',
    caseNumber: 'TRF-5014',
    customerId: 'cust-5',
    customerName: 'Edward Norton-Smith',
    title: 'Clark County Trustee Sale Surplus',
    claimType: 'Mortgage Foreclosure Overage',
    status: 'documents_required',
    priority: 'medium',
    claimAmount: 43200,
    expectedFee: 12960,
    feePercentage: 30,
    recoveredAmount: 0,
    assignedAgentId: 'agent-4',
    assignedAgentName: 'Sarah Jenkins',
    filingJurisdiction: 'Eighth Judicial District Court, Nevada',
    caseRefNumber: 'A-26-89104-C',
    filingDate: undefined,
    hearingDate: undefined,
    dateCreated: '2026-05-05T14:00:00Z',
    lastUpdated: '2026-09-14T11:00:00Z',
    description: 'Foreclosure sale by private trustee; funds deposited with county clerk.',
    notes: 'Awaiting client signature on notarized Power of Attorney form.'
  },
  {
    id: 'case-5',
    caseNumber: 'TRF-5015',
    customerId: 'cust-6',
    customerName: 'Fiona O\'Connor',
    title: 'King County Tax Auction Excess Proceeds',
    claimType: 'Tax Deed Surplus',
    status: 'assessment',
    priority: 'medium',
    claimAmount: 95700,
    expectedFee: 23925,
    feePercentage: 25,
    recoveredAmount: 0,
    assignedAgentId: 'agent-2',
    assignedAgentName: 'Elena Rostova',
    filingJurisdiction: 'King County Superior Court, Washington',
    caseRefNumber: '26-2-04981-1',
    filingDate: '2026-06-15',
    hearingDate: '2026-10-04',
    dateCreated: '2026-05-25T10:15:00Z',
    lastUpdated: '2026-09-16T15:30:00Z',
    description: 'Auditor assessment period complete; motion filed for surplus distribution.',
    notes: 'Title report clear of junior encumbrances.'
  },
  {
    id: 'case-6',
    caseNumber: 'TRF-5016',
    customerId: 'cust-8',
    customerName: 'Hannah Lindqvist',
    title: 'Cook County Judicial Foreclosure Surplus',
    claimType: 'Mortgage Foreclosure Overage',
    status: 'under_review',
    priority: 'urgent',
    claimAmount: 185000,
    expectedFee: 46250,
    feePercentage: 25,
    recoveredAmount: 0,
    assignedAgentId: 'agent-2',
    assignedAgentName: 'Elena Rostova',
    filingJurisdiction: 'Circuit Court of Cook County, Chancery Division',
    caseRefNumber: '2026-CH-04829',
    filingDate: '2026-07-15',
    hearingDate: undefined,
    dateCreated: '2026-07-02T13:00:00Z',
    lastUpdated: '2026-09-17T11:15:00Z',
    description: 'Commercial property foreclosure generated record excess funds.',
    notes: 'Legal team reviewing competing claims from secondary creditor.'
  },
  {
    id: 'case-7',
    caseNumber: 'TRF-5017',
    customerId: 'cust-10',
    customerName: 'Jacqueline Mercer',
    title: 'Dallas County Sheriff Sale Surplus',
    claimType: 'Tax Deed Surplus',
    status: 'in_progress',
    priority: 'medium',
    claimAmount: 72400,
    expectedFee: 18100,
    feePercentage: 25,
    recoveredAmount: 0,
    assignedAgentId: 'agent-1',
    assignedAgentName: 'Marcus Vance',
    filingJurisdiction: '192nd Civil District Court, Dallas County',
    caseRefNumber: 'DC-26-09148',
    filingDate: '2026-08-05',
    hearingDate: '2026-10-18',
    dateCreated: '2026-08-01T15:00:00Z',
    lastUpdated: '2026-09-18T10:00:00Z',
    description: 'Surplus funds verified with Dallas County District Clerk.',
    notes: 'Citation issued to former mortgage lender.'
  }
];

export const MOCK_TASKS: Task[] = [
  {
    id: 'task-1',
    title: 'Review court order draft for Beatrice Montgomery',
    description: 'Ensure all lien waivers are attached prior to filing motion with Miami-Dade clerk.',
    status: 'pending',
    priority: 'urgent',
    type: 'document_review',
    assignedAgentId: 'agent-2',
    assignedAgentName: 'Elena Rostova',
    dueDate: '2026-09-19T17:00:00Z',
    relatedCustomerId: 'cust-2',
    relatedCustomerName: 'Beatrice Montgomery',
    relatedCaseId: 'case-2',
    relatedCaseNumber: 'TRF-5012',
    dateCreated: '2026-09-17T09:00:00Z'
  },
  {
    id: 'task-2',
    title: 'Call Victor Delgado to verify DocuSign completion',
    description: 'Check if client received the recovery agreement email and assist with e-sign.',
    status: 'pending',
    priority: 'high',
    type: 'call',
    assignedAgentId: 'agent-1',
    assignedAgentName: 'Marcus Vance',
    dueDate: '2026-09-18T16:00:00Z',
    dateCreated: '2026-09-18T08:30:00Z'
  },
  {
    id: 'task-3',
    title: 'Submit certified deed copy to Maricopa County Treasurer',
    description: 'Diana Kaufman case requires certified deed from county recorder.',
    status: 'in_progress',
    priority: 'high',
    type: 'court_filing',
    assignedAgentId: 'agent-1',
    assignedAgentName: 'Marcus Vance',
    dueDate: '2026-09-20T12:00:00Z',
    relatedCustomerId: 'cust-4',
    relatedCustomerName: 'Diana Kaufman',
    relatedCaseId: 'case-3',
    relatedCaseNumber: 'TRF-5013',
    dateCreated: '2026-09-16T11:00:00Z'
  },
  {
    id: 'task-4',
    title: 'Follow up with Edward Norton-Smith regarding notarization',
    description: 'Client needs guidance locating a local mobile notary for POA.',
    status: 'pending',
    priority: 'medium',
    type: 'follow_up',
    assignedAgentId: 'agent-4',
    assignedAgentName: 'Sarah Jenkins',
    dueDate: '2026-09-19T15:00:00Z',
    relatedCustomerId: 'cust-5',
    relatedCustomerName: 'Edward Norton-Smith',
    relatedCaseId: 'case-4',
    relatedCaseNumber: 'TRF-5014',
    dateCreated: '2026-09-15T14:00:00Z'
  },
  {
    id: 'task-5',
    title: 'Draft petition for surplus release in King County',
    description: 'Prepare petition for Fiona O\'Connor case before hearing deadline.',
    status: 'completed',
    priority: 'medium',
    type: 'court_filing',
    assignedAgentId: 'agent-2',
    assignedAgentName: 'Elena Rostova',
    dueDate: '2026-09-16T18:00:00Z',
    completedDate: '2026-09-16T15:00:00Z',
    relatedCustomerId: 'cust-6',
    relatedCustomerName: 'Fiona O\'Connor',
    relatedCaseId: 'case-5',
    relatedCaseNumber: 'TRF-5015',
    dateCreated: '2026-09-12T10:00:00Z'
  },
  {
    id: 'task-6',
    title: 'Intake qualification call with Franklin Manning',
    description: 'Review $215k Harris County foreclosure overage details.',
    status: 'pending',
    priority: 'high',
    type: 'intake',
    assignedAgentId: 'agent-1',
    assignedAgentName: 'Marcus Vance',
    dueDate: '2026-09-18T18:00:00Z',
    dateCreated: '2026-09-18T11:00:00Z'
  }
];

export const MOCK_CALLS: Call[] = [
  {
    id: 'call-1',
    agentId: 'agent-1',
    agentName: 'Marcus Vance',
    customerId: 'cust-4',
    customerName: 'Diana Kaufman',
    direction: 'outbound',
    realPhoneNumber: '+1 (602) 492-6715',
    maskedPhoneNumber: '+1 (***) ***-6715',
    durationSeconds: 312,
    status: 'completed',
    outcome: 'information_provided',
    timestamp: '2026-09-18T09:10:00Z',
    notes: 'Informed client of certified deed submission to Maricopa Treasurer. Client is satisfied.'
  },
  {
    id: 'call-2',
    agentId: 'agent-1',
    agentName: 'Marcus Vance',
    leadId: 'lead-3',
    leadName: 'Franklin Manning',
    direction: 'outbound',
    realPhoneNumber: '+1 (832) 555-0128',
    maskedPhoneNumber: '+1 (***) ***-0128',
    durationSeconds: 520,
    status: 'completed',
    outcome: 'contract_requested',
    timestamp: '2026-09-18T10:30:00Z',
    notes: 'Discussed $215,000 foreclosure overage. Client requested contingency agreement via email.'
  },
  {
    id: 'call-3',
    agentId: 'agent-2',
    agentName: 'Elena Rostova',
    customerId: 'cust-2',
    customerName: 'Beatrice Montgomery',
    direction: 'outbound',
    realPhoneNumber: '+1 (305) 714-8820',
    maskedPhoneNumber: '+1 (***) ***-8820',
    durationSeconds: 410,
    status: 'completed',
    outcome: 'information_provided',
    timestamp: '2026-09-17T16:00:00Z',
    notes: 'Updated client on court hearing scheduled for Sept 25. Reassured client regarding timeline.'
  },
  {
    id: 'call-4',
    agentId: 'agent-4',
    agentName: 'Sarah Jenkins',
    leadId: 'lead-2',
    leadName: 'Samantha Garrison',
    direction: 'outbound',
    realPhoneNumber: '+1 (407) 555-0144',
    maskedPhoneNumber: '+1 (***) ***-0144',
    durationSeconds: 0,
    status: 'voicemail',
    outcome: 'call_back_requested',
    timestamp: '2026-09-16T16:00:00Z',
    notes: 'Left detailed voicemail regarding Orange County tax deed surplus.'
  },
  {
    id: 'call-5',
    agentId: 'agent-2',
    agentName: 'Elena Rostova',
    customerId: 'cust-8',
    customerName: 'Hannah Lindqvist',
    direction: 'inbound',
    realPhoneNumber: '+1 (312) 554-9012',
    maskedPhoneNumber: '+1 (***) ***-9012',
    durationSeconds: 625,
    status: 'completed',
    outcome: 'information_provided',
    timestamp: '2026-09-17T11:15:00Z',
    notes: 'Client called asking about secondary creditor claims in Cook County case.'
  }
];

export const MOCK_PAYMENTS: Payment[] = [
  {
    id: 'pay-1',
    referenceNumber: 'PAY-4011',
    caseId: 'case-1',
    caseNumber: 'TRF-5011',
    customerId: 'cust-1',
    customerName: 'Arthur Pendleton',
    amount: 84500,
    feeAmount: 21125,
    clientPayoutAmount: 63375,
    type: 'recovery_payout',
    method: 'wire_transfer',
    status: 'completed',
    date: '2026-05-22T14:00:00Z',
    transactionReference: 'WT-2026-89104',
    notes: 'Net disbursement sent to Arthur Pendleton after 25% contingency fee deducted.'
  },
  {
    id: 'pay-2',
    referenceNumber: 'PAY-4012',
    caseId: 'case-1',
    caseNumber: 'TRF-5011',
    customerId: 'cust-1',
    customerName: 'Arthur Pendleton',
    amount: 21125,
    feeAmount: 21125,
    clientPayoutAmount: 0,
    type: 'contingency_fee',
    method: 'direct_deposit',
    status: 'completed',
    date: '2026-05-22T14:05:00Z',
    transactionReference: 'FEE-2026-3391',
    notes: 'Trust Funds Recovery earned fee deposited into corporate operating account.'
  },
  {
    id: 'pay-3',
    referenceNumber: 'PAY-4013',
    caseId: 'case-7',
    caseNumber: 'TRF-5017',
    customerId: 'cust-11',
    customerName: 'Kenneth Bauer',
    amount: 112000,
    feeAmount: 28000,
    clientPayoutAmount: 84000,
    type: 'recovery_payout',
    method: 'ach',
    status: 'completed',
    date: '2026-08-26T10:30:00Z',
    transactionReference: 'ACH-2026-77821',
    notes: 'Massachusetts Land Court payout processed successfully.'
  },
  {
    id: 'pay-4',
    referenceNumber: 'PAY-4014',
    caseId: 'case-2',
    caseNumber: 'TRF-5012',
    customerId: 'cust-2',
    customerName: 'Beatrice Montgomery',
    amount: 142000,
    feeAmount: 35500,
    clientPayoutAmount: 106500,
    type: 'court_disbursement',
    method: 'wire_transfer',
    status: 'pending',
    date: '2026-09-17T09:00:00Z',
    transactionReference: 'FL-CRT-DISB-01',
    notes: 'Pending final order of distribution from 11th Judicial Circuit Court.'
  }
];

export const MOCK_DOCUMENTS: CrmDocument[] = [
  {
    id: 'doc-1',
    title: 'Signed Contingency Fee Agreement',
    fileName: 'Arthur_Pendleton_Retainer_Signed.pdf',
    fileSize: '1.2 MB',
    fileType: 'pdf',
    category: 'contract',
    status: 'verified',
    relatedCustomerId: 'cust-1',
    relatedCustomerName: 'Arthur Pendleton',
    relatedCaseId: 'case-1',
    relatedCaseNumber: 'TRF-5011',
    uploadedBy: 'Marcus Vance',
    uploadDate: '2026-01-16T11:20:00Z'
  },
  {
    id: 'doc-2',
    title: 'Sacramento County Superior Court Release Order',
    fileName: 'Sacramento_Surplus_Release_Order.pdf',
    fileSize: '3.4 MB',
    fileType: 'pdf',
    category: 'court_order',
    status: 'verified',
    relatedCustomerId: 'cust-1',
    relatedCustomerName: 'Arthur Pendleton',
    relatedCaseId: 'case-1',
    relatedCaseNumber: 'TRF-5011',
    uploadedBy: 'Robert Chen',
    uploadDate: '2026-05-18T16:00:00Z'
  },
  {
    id: 'doc-3',
    title: 'Motion for Release of Foreclosure Surplus',
    fileName: 'Miami_Dade_Motion_Surplus_Release.pdf',
    fileSize: '2.1 MB',
    fileType: 'pdf',
    category: 'claim_filing',
    status: 'verified',
    relatedCustomerId: 'cust-2',
    relatedCustomerName: 'Beatrice Montgomery',
    relatedCaseId: 'case-2',
    relatedCaseNumber: 'TRF-5012',
    uploadedBy: 'Elena Rostova',
    uploadDate: '2026-03-02T14:15:00Z'
  },
  {
    id: 'doc-4',
    title: 'Client Government ID & Proof of Prior Ownership',
    fileName: 'Beatrice_Montgomery_ID_Deed.pdf',
    fileSize: '4.8 MB',
    fileType: 'pdf',
    category: 'id_verification',
    status: 'verified',
    relatedCustomerId: 'cust-2',
    relatedCustomerName: 'Beatrice Montgomery',
    relatedCaseId: 'case-2',
    relatedCaseNumber: 'TRF-5012',
    uploadedBy: 'Elena Rostova',
    uploadDate: '2026-02-06T10:00:00Z'
  },
  {
    id: 'doc-5',
    title: 'Maricopa County Surplus Claim Form',
    fileName: 'Diana_Kaufman_Maricopa_Claim.pdf',
    fileSize: '1.9 MB',
    fileType: 'pdf',
    category: 'claim_filing',
    status: 'pending_review',
    relatedCustomerId: 'cust-4',
    relatedCustomerName: 'Diana Kaufman',
    relatedCaseId: 'case-3',
    relatedCaseNumber: 'TRF-5013',
    uploadedBy: 'Marcus Vance',
    uploadDate: '2026-05-11T09:40:00Z'
  },
  {
    id: 'doc-6',
    title: 'Limited Power of Attorney (Awaiting Notarization)',
    fileName: 'Edward_Norton_Smith_POA_Draft.pdf',
    fileSize: '840 KB',
    fileType: 'pdf',
    category: 'power_of_attorney',
    status: 'draft',
    relatedCustomerId: 'cust-5',
    relatedCustomerName: 'Edward Norton-Smith',
    relatedCaseId: 'case-4',
    relatedCaseNumber: 'TRF-5014',
    uploadedBy: 'Sarah Jenkins',
    uploadDate: '2026-05-08T15:30:00Z'
  }
];

export const MOCK_NOTIFICATIONS: CrmNotification[] = [
  {
    id: 'notif-1',
    userId: 'all',
    title: 'Hearing Scheduled: Beatrice Montgomery',
    message: '11th Judicial Circuit Court hearing set for Sept 25 at 10:00 AM EST.',
    type: 'case_update',
    read: false,
    timestamp: '2026-09-17T16:05:00Z',
    link: '/admin/cases/case-2'
  },
  {
    id: 'notif-2',
    userId: 'agent-1',
    title: 'Contract Requested by Lead',
    message: 'Franklin Manning requested contingency fee agreement for $215k overage.',
    type: 'lead_assigned',
    read: false,
    timestamp: '2026-09-18T10:35:00Z',
    link: '/agent/leads'
  },
  {
    id: 'notif-3',
    userId: 'admin',
    title: 'Payment Processed: $112,000',
    message: 'ACH payout completed for Kenneth Bauer case (TRF-5017).',
    type: 'payment_received',
    read: true,
    timestamp: '2026-08-26T10:32:00Z',
    link: '/admin/payments'
  },
  {
    id: 'notif-4',
    userId: 'agent-2',
    title: 'Task Due Tomorrow',
    message: 'Review court order draft for Beatrice Montgomery is due Sept 19.',
    type: 'task_due',
    read: false,
    timestamp: '2026-09-18T08:00:00Z',
    link: '/agent/tasks'
  }
];

export const MOCK_ACTIVITIES: ActivityEvent[] = [
  {
    id: 'act-1',
    userId: 'agent-1',
    userName: 'Marcus Vance',
    userRole: 'agent',
    action: 'Logged outbound call',
    type: 'call',
    details: 'Called Diana Kaufman. Duration: 5m 12s. Outcome: Information provided.',
    targetId: 'cust-4',
    targetName: 'Diana Kaufman',
    timestamp: '2026-09-18T09:10:00Z'
  },
  {
    id: 'act-2',
    userId: 'agent-1',
    userName: 'Marcus Vance',
    userRole: 'agent',
    action: 'Updated lead stage',
    type: 'lead',
    details: 'Moved Franklin Manning from "contacted" to "interested" (Score: 96).',
    targetId: 'lead-3',
    targetName: 'Franklin Manning',
    timestamp: '2026-09-18T10:35:00Z'
  },
  {
    id: 'act-3',
    userId: 'agent-2',
    userName: 'Elena Rostova',
    userRole: 'agent',
    action: 'Completed task',
    type: 'task',
    details: 'Draft petition for surplus release in King County marked completed.',
    targetId: 'task-5',
    targetName: 'Task #5',
    timestamp: '2026-09-16T15:00:00Z'
  },
  {
    id: 'act-4',
    userId: 'admin-1',
    userName: 'System Administrator',
    userRole: 'admin',
    action: 'Approved payout disbursement',
    type: 'payment',
    details: 'Approved $84,000 ACH net client disbursement for case TRF-5017.',
    targetId: 'pay-3',
    targetName: 'PAY-4013',
    timestamp: '2026-08-26T10:30:00Z'
  }
];

export const MOCK_COMMUNICATIONS: Communication[] = [
  {
    id: 'comm-1',
    type: 'email',
    customerId: 'cust-4',
    customerName: 'Diana Kaufman',
    agentId: 'agent-1',
    agentName: 'Marcus Vance',
    subject: 'Maricopa County Surplus Claim Update',
    content: 'Hi Diana, We have submitted the certified deed copy to the county treasurer. We expect a response within 14 business days.',
    status: 'sent',
    timestamp: '2026-09-18T09:30:00Z'
  },
  {
    id: 'comm-2',
    type: 'sms',
    customerId: 'cust-2',
    customerName: 'Beatrice Montgomery',
    agentId: 'agent-2',
    agentName: 'Elena Rostova',
    content: 'Hello Beatrice, just confirming our phone call today: your court hearing is set for Sept 25. No action needed from you at this time.',
    status: 'sent',
    timestamp: '2026-09-17T16:15:00Z'
  }
];
